[package]
name = "bb-helper"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tempfile = "3.24"
tokio = { version = "1.48", default-features = false }

[features]
file_stream = ["tokio/fs", "tokio/io-util"]
resolvable = ["tokio/fs", "tokio/rt"]
